config/routes.rb
Rails.application.routes.draw do

  resources :sections, only: [:show, :edit, :update, :destroy] do
    resources :sub_sections, shallow: true
  end

  resources :books do
    resources :sections, only: [:index, :new, :create]
  end

  resources :children do
    resources :completed_sections, except: :update
  end

  resources :organizations do
    resources :clubs, only: [:index, :new, :create]
  end

  resources :clubs, only: [:show, :edit, :update, :destroy] do
    resources :teams
  end


  # devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root to: "home#index"
end

app/models/club.rb
class Club
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :children
  embeds_many :teams

  field :name, type: String
  validates_presence_of :name
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = organization.clubs.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clubs }
    end
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/new
  def new
    @club = organization.clubs.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = organization.clubs.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render json: @club, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to organization_clubs_url(@club.organization) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    def organization_id
      params.require(:organization_id)
    end

    def organization
      @organization ||= Organization.find(organization_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.fetch(:club, {}).permit(:name)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= simple_form_for(@club) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<div class="page-header">
  <%= link_to clubs_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @club, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing club</h1>
</div>

<%= render 'form' %>

app/views/clubs/index.html.erb
<div class="page-header">
  <%= link_to new_club_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Club
  <% end %>
  <h1>Listing clubs</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clubs) do |club| %>
            <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clubs/new.html.erb
<div class="page-header">
  <%= link_to clubs_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New club</h1>
</div>

<%= render 'form' %>

app/views/clubs/show.html.erb
<div class="page-header">
  <%= link_to clubs_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_club_path(@club), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show club</h1>
</div>

<dl class="dl-horizontal">
</dl>