config/routes.rb
Rails.application.routes.draw do

  resources :sections, only: [:show, :edit, :update, :destroy] do
    resources :sub_sections, shallow: true
  end

  resources :books do
    resources :sections, only: [:index, :new, :create]
  end

  resources :children do
    resources :completed_sections, except: :update
  end

  resources :organizations do
    resources :clubs, only: [:index, :new, :create]
  end

  resources :clubs, only: [:show, :edit, :update, :destroy] do
    resources :teams
  end


  # devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root to: "home#index"
end

app/models/sub_section.rb
class SubSection
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Orderable

  field :name, type: String, default: ""
  field :description, type: String, default: ""

  belongs_to :section
  orderable

  def name
    read_attribute(:name).blank? ? position : read_attribute(:name)
  end
end

app/controllers/sub_sections_controller.rb
class SubSectionsController < ApplicationController
  before_action :set_sub_section, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @sub_sections = section.sub_sections.all
    respond_with(@sub_sections)
  end

  def show
    respond_with(@sub_section)
  end

  def new
    @sub_section = SubSection.new
    respond_with(@sub_section)
  end

  def edit
  end

  def create
    @sub_section = SubSection.new(sub_section_params)
    @sub_section.save
    respond_with(@sub_section)
  end

  def update
    @sub_section.update(sub_section_params)
    respond_with(@sub_section)
  end

  def destroy
    @sub_section.destroy
    respond_with(@sub_section.section, @sub_section)
  end

  private
    def set_sub_section
      @sub_section = SubSection.find(params[:id])
    end

    def section
      @section ||= Section.where(id: params.require(:section_id)).first
    end

    def sub_section_params
      params.require(:sub_section).permit(:name, :description, :section_id)
    end
end

app/helpers/sub_sections_helper.rb
module SubSectionsHelper
end

app/views/sub_sections/_form.html.erb
<%= simple_form_for(@sub_section) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :section_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sub_sections/edit.html.erb
<div class="page-header">
  <%= link_to sub_sections_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @sub_section, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing sub_section</h1>
</div>

<%= render 'form' %>

app/views/sub_sections/index.html.erb
<div class="page-header">
  <%= link_to new_sub_section_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Sub section
  <% end %>
  <h1>Listing sub_sections</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Section</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @sub_sections) do |sub_section| %>
            <td><%= sub_section.name %></td>
            <td><%= sub_section.description %></td>
            <td><%= sub_section.section_id %></td>
            <td><%= link_to 'Show', sub_section %></td>
        <td><%= link_to 'Edit', edit_sub_section_path(sub_section) %></td>
        <td><%= link_to 'Destroy', sub_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sub_sections/new.html.erb
<div class="page-header">
  <%= link_to sub_sections_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New sub_section</h1>
</div>

<%= render 'form' %>

app/views/sub_sections/show.html.erb
<div class="page-header">
  <%= link_to sub_sections_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_sub_section_path(@sub_section), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show sub_section</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @sub_section.name %></dd>

  <dt>Description:</dt>
  <dd><%= @sub_section.description %></dd>

  <dt>Section:</dt>
  <dd><%= @sub_section.section_id %></dd>

</dl>