config/routes.rb
Rails.application.routes.draw do

  resources :sections, only: [:show, :edit, :update, :destroy] do
    resources :sub_sections, shallow: true
  end

  resources :books do
    resources :sections, only: [:index, :new, :create]
  end

  resources :children do
    resources :completed_sections, except: :update
  end

  resources :organizations do
    resources :clubs, only: [:index, :new, :create]
  end

  resources :clubs, only: [:show, :edit, :update, :destroy] do
    resources :teams
  end


  # devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root to: "home#index"
end

app/models/section.rb
class Section
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Orderable

  field :name, type: String

  belongs_to :book

  has_many :sub_sections

  validates_presence_of :name, :book
  accepts_nested_attributes_for :sub_sections
  orderable

  def book_name
    book.present? ? book.name.to_s : ""
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @sections = book.sections
    respond_with(@sections)
  end

  def show
    respond_with(@section)
  end

  def new
    @section = Section.new
    respond_with(@section)
  end

  def edit
  end

  def create
    @section = book.sections.new(section_params)
    @section.save
    respond_with(@section)
  end

  def update
    @section.update(section_params)
    respond_with(@section)
  end

  def destroy
    @section.destroy
    respond_with(@section, location: book_sections_url(@section.book))
  end

  private
    def set_section
      @section = Section.find(params[:id])
    end

    def book_id
      params.require(:book_id)
    end

    def book
      @book ||= Book.find(book_id)
    end

    def section_params
      params.fetch(:section, {}).permit(
          :name,
          :book_id,
          :position,
          {sub_sections_attributes:
              [:name, :decription, :position]}
          )
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= simple_nested_form_for(@section, html: { class: "" }) do |f| %>
  <% if @section.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h4>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name %>
  </div>
  <div class="form-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Sub-sections</h3>
      </div>

      <ul id="section-sub_sections" class="panel-body list-unstyled">
      <%= f.fields_for :sub_sections, wrapper:false do |ff| %>
        <li>
          <div class="row">
          <% if ff.object.persisted? %>
          <div class="form-group col-sm-4">
            <label class="control-label">Name</label>
            <p class="form-control-static">
              <%= link_to ff.object.name, edit_sub_section_path(ff.object) %>
            </p>
          </div>
          <% else %>
            <%= ff.input :name, wrapper_html: {class: "col-sm-4"} %>
            <%= ff.input :description, wrapper_html: {class: "col-sm-4"} %>
          <% end %>
          <div class="form-group col-sm-4 pull-right">
            <label class="control-label"></label>
            <p class="form-control-static">
              <%= ff.link_to_remove "Remove this sub-section" %>
            </p>
          </div>
          </div>
        </li>
      <% end %>
      </ul>

      <div class="panel-footer">
        <%= f.link_to_add "Add a sub-section", :sub_sections, data: { target: "#section-sub_sections" } %>
      </div>
    </div>
  </div>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/sections/edit.html.erb
<div class="page-header">
  <%= link_to book_path(@section.book), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @section, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing <%= @section.name.titleize %></h1>
</div>

<%= render 'form' %>

app/views/sections/index.html.erb
<div class="page-header">
  <%= link_to new_section_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Section
  <% end %>
  <h1>Listing sections</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Book</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @sections) do |section| %>
            <td><%= section.name %></td>
            <td><%= section.book_name %></td>
            <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sections/new.html.erb
<div class="page-header">
  <%= link_to sections_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New section</h1>
</div>

<%= render 'form' %>

app/views/sections/show.html.erb
<div class="page-header">
  <%= link_to book_path(@section.book), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_section_path(@section), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @section.name.to_s.titleize %></h1>
</div>

<% if @section.sub_sections.present? %>
  <ol class="">
    <% @section.sub_sections.each do |s| %>
      <li>
        <%= link_to s.name, sub_section_path(s) %>
      </li>
    <% end %>
  </ol>
<% else %>
  <p class="text-muted">No sub-sections have been added yet</p>
<% end %>