config/routes.rb
Rails.application.routes.draw do

  resources :sections, only: [:show, :edit, :update, :destroy] do
    resources :sub_sections, shallow: true
  end

  resources :books do
    resources :sections, only: [:index, :new, :create]
  end

  resources :children do
    resources :completed_sections, except: :update
  end

  resources :organizations do
    resources :clubs, only: [:index, :new, :create]
  end

  resources :clubs, only: [:show, :edit, :update, :destroy] do
    resources :teams
  end


  # devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root to: "home#index"
end

app/models/book.rb
class Book
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Orderable
  orderable

  field :name, type: String, default: "Book"

  has_many :sections
  accepts_nested_attributes_for :sections

  has_many :children_in_progress,
           class_name: "Child",
           inverse_of: "current_book"
  has_and_belongs_to_many :children_who_have_completed,
           class_name: "Child",
           inverse_of: "completed_books"

  def get_next
    next_item
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, {sections_attributes: [:name, :position]})
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_nested_form_for(@book, html: { class: "" }) do |f| %>
  <% if @book.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h4>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name %>
  </div>
  <div class="form-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Sections</h3>
      </div>
      <div id="book-sections" class="panel-body">
      <%= f.fields_for :sections do |ff| %>
        <div class="row">
          <% if ff.object.persisted? %>
          <div class="form-group">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-4">
              <p class="form-control-static">
                <%= link_to ff.object.name, edit_section_path(ff.object) %>
              </p>
            </div>
          </div>
          <% else %>
            <%= ff.input :name, wrapper_html: {class: "col-sm-4"} %>
          <% end %>
          <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-4">
              <p class="form-control-static">
                <%= ff.link_to_remove "Remove this section" %>
              </p>
            </div>
          </div>

        </div>
      <% end %>
      </div>
      <div class="panel-footer">
        <%= f.link_to_add "Add a section", :sections, data: { target: "#book-sections" } %>
      </div>
    </div>
  </div>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<div class="page-header">
  <%= link_to books_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @book, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing book</h1>
</div>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="page-header">
  <%= link_to new_book_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Book
  <% end %>
  <h1>Listing books</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @books) do |book| %>
            <td><%= book.name %></td>
            <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<div class="page-header">
  <%= link_to books_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New book</h1>
</div>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="page-header">
  <%= link_to books_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_book_path(@book), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @book.name.to_s.titleize %></h1>
</div>

<% if @book.sections.present? %>
  <ul class="list-unstyled">
    <% @book.sections.each do |s| %>
      <li>
        <%= link_to s.name, section_path(s) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="text-muted">No sections have been added yet</p>
<% end %>